### ISSUE TITLE
Broken resources links

### ISSUE THREAD

**Issue by securingdev** [githubsatelliteworkshops/codeql#3]
It appears the following section in the README.md file has broken links:

## :books: Resources
- [Learning CodeQL](https://help.semmle.com/QL/learn-ql)
- [Learning CodeQL for Java](https://help.semmle.com/QL/learn-ql/java/ql-for-java.html)
- [Learning CodeQL for JavaScript](https://help.semmle.com/QL/learn-ql/javascript/ql-for-javascript.html)
- [Using the CodeQL extension for VS Code](https://help.semmle.com/codeql/codeql-for-vscode.html)

These all seem to point to the *Semmle* home page, which provides a **404 Error**. Normally I'd just PR with the correct links, but I don't know what pages these have translated to now that these resources have migrated to https://codeql.github.com/ 😅

**Comment by jf205** [comment]
Good spot 👍🏻  
We had redirects in place for these until recently. I think the most sensible replacements are
* [CodeQL documentation homepage](https://codeql.github.com/docs/)
* [CodeQL for Java](https://codeql.github.com/docs/codeql-language-guides/codeql-for-java/)
* [CodeQL for JavaScript](https://codeql.github.com/docs/codeql-language-guides/codeql-for-javascript/)
* [CodeQL for Visual Studio Code](https://codeql.github.com/docs/codeql-for-visual-studio-code/)

**Comment by securingdev** [comment]
Sweet - I'll go ahead and update these with a PR 😄

**Comment by securingdev** [comment]
Reopening issue so that I can close it with the PR appropriately 🤦
