### ISSUE TITLE
Broken links in "What's Next"

### ISSUE THREAD

**Issue by securingdev** [githubsatelliteworkshops/codeql#7]
👋 Hi folks! I noticed the following two links were broken, and was going to put together a PR to fix this. What links would you recommend as replacements for these old Semmle.com links?

**Broken Links**: 
- Read the [tutorial on analyzing data flow in Java](https://help.semmle.com/QL/learn-ql/java/dataflow.html) (which maybe could be replaced with [this link](https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-java/#analyzing-data-flow-in-java)).
- Go through more [CodeQL training materials for Java](https://help.semmle.com/QL/learn-ql/ql-training.html#codeql-and-variant-analysis-for-java) (which maybe could be replaced with  [this link](https://codeql.github.com/docs/codeql-language-guides/codeql-for-java/)).

Thoughts?

**Comment by felicitymay** [comment]
Hi. Thanks for asking about these links.

I think you're spot on with the first replacement link. For the second one, that also sounds as if it might be the right answer. 

The second link was probably originally to a list of links to training slides like these: https://help.semmle.com/QL/ql-training/java/intro-ql-java#1, but the future of these articles is under discussion so your suggestion might well be safer.
